import { NgModule } from '@angular/core';
import {
  MatButtonModule, 
  MatCardModule,
  MatCheckboxModule,
  MatIconModule,
  MatInputModule,
  MatFormFieldModule,
  MatMenuModule,
  MatPaginatorModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatSelectModule,
  MatTableModule,
  MatToolbarModule,
  MatDialogModule,
  MatProgressBarModule,
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    MatButtonModule, 
    MatCardModule,
    MatCheckboxModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatMenuModule, 
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatTableModule,
    MatToolbarModule,
    MatDialogModule,
    MatProgressBarModule,
  ],
  exports: [
    MatButtonModule, 
    MatCardModule,
    MatCheckboxModule,
    MatIconModule,
    MatInputModule,
    MatFormFieldModule,
    MatMenuModule, 
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatTableModule,
    MatToolbarModule,
    MatDialogModule,
    MatProgressBarModule,
  ]
})
export class MaterialDesignModule { }
